### ISSUE TITLE
Cannot start robot-server on buildout.coredev 5.2

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.app.robotframework#97]
```
[ale@emily plone3]$ ./bin/robot-server -vvvvvvvd Products.CMFPlone.testing.PRODUCTS_CMFPLONE_ROBOT_TESTING
Traceback (most recent call last):
  File "./bin/robot-server", line 268, in <module>
    import plone.app.robotframework.server
  File "/home/ale/Code/plone/plone3/src/plone.app.robotframework/src/plone/app/robotframework/__init__.py", line 4, in <module>
    from plone.app.robotframework.server import Zope2Server
  File "/home/ale/Code/plone/plone3/src/plone.app.robotframework/src/plone/app/robotframework/server.py", line 21, in <module>
    from plone.app.robotframework.reload import ForkLoop
  File "/home/ale/Code/plone/plone3/src/plone.app.robotframework/src/plone/app/robotframework/reload.py", line 7, in <module>
    from Signals.SignalHandler import SignalHandler
ModuleNotFoundError: No module named 'Signals'
```

**Comment by ale-rt** [comment]
The reason seems to be that the Signal module was moved to ZServer.
https://github.com/zopefoundation/ZServer/commit/ee3cb3c7576df0de96d0fe96fbdc7912efed3049
